In [3]:
import numpy as np
import array

In [5]:
np.array([1,2,3,4,5,6,7,8])

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
np.array([[1,3],[3,4],[4,7]])

array([[1, 3],
       [3, 4],
       [4, 7]])

In [10]:
type(np)

module

In [11]:
np.array([1,2,3],ndmin=3)

array([[[1, 2, 3]]])

In [13]:
np.array([[1,2,3],[3,4,5],[4,6,7]],ndmin=3)

array([[[1, 2, 3],
        [3, 4, 5],
        [4, 6, 7]]])

In [18]:
np.array([1,2,3] ,dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [34]:
arr =np.array([(1,2),(4,5)],dtype =[ ('a','<i4'),('b','<i8')])

In [30]:
arr


array([(1, 2), (4, 5)], dtype=[('a', '<i4'), ('b', '<i8')])

In [32]:
type(arr[0][0])

numpy.int32

In [35]:
type(arr[0][1])

numpy.int64

In [36]:
arr[0]

(1, 2)

In [39]:
type(arr[0][1])

numpy.int64

In [38]:
arr

array([(1, 2), (4, 5)], dtype=[('a', '<i4'), ('b', '<i8')])

In [40]:
np.mat(arr)

matrix([[(1, 2), (4, 5)]], dtype=[('a', '<i4'), ('b', '<i8')])

In [41]:
arr


array([(1, 2), (4, 5)], dtype=[('a', '<i4'), ('b', '<i8')])

In [45]:
arr = np.array([[1,3],[3,4]])

In [46]:
arr

array([[1, 3],
       [3, 4]])

In [52]:
mat = np.mat(arr)

In [53]:
mat

matrix([[1, 3],
        [3, 4]])

In [49]:
l =[1,3,6,9]

In [50]:
np.asarray(l)

array([1, 3, 6, 9])

In [51]:
np.asanyarray(l)

array([1, 3, 6, 9])

In [54]:
np.asarray(mat)

array([[1, 3],
       [3, 4]])

In [55]:
np.asanyarray(mat)

matrix([[1, 3],
        [3, 4]])

In [56]:
issubclass(np.matrix, np.ndarray)

True

In [57]:
issubclass(np.ndarray,np.matrix)

False

In [58]:
arr


array([[1, 3],
       [3, 4]])

In [59]:
a = arr

In [60]:
b = np.copy(a)

In [61]:
b

array([[1, 3],
       [3, 4]])

In [62]:
b = np.copy(arr)

In [63]:
b

array([[1, 3],
       [3, 4]])

In [65]:
arr[0][0]=67

In [66]:
arr

array([[67,  3],
       [ 3,  4]])

In [67]:
a

array([[67,  3],
       [ 3,  4]])

In [68]:
b

array([[1, 3],
       [3, 4]])

In [69]:
a[0][0]

67

In [70]:
arr[0:10]

array([[67,  3],
       [ 3,  4]])

In [71]:
arr[-1]

array([3, 4])

In [72]:
arr[::-1]

array([[ 3,  4],
       [67,  3]])

In [73]:
for i in arr:
    print(i)

[67  3]
[3 4]


In [74]:
b =np.fromfunction(lambda i, j: i==j,(4,4))

In [75]:
b

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [76]:
np.fromfunction(lambda i, j: i*j,(4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [77]:
np.fromfunction(lambda i, j: i/j,(4,4))

C:\Users\SAMARTH\AppData\Local\Temp/ipykernel_8912/2745615430.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.fromfunction(lambda i, j: i/j,(4,4))
C:\Users\SAMARTH\AppData\Local\Temp/ipykernel_8912/2745615430.py:1: RuntimeWarning: invalid value encountered in true_divide
  np.fromfunction(lambda i, j: i/j,(4,4))


array([[       nan, 0.        , 0.        , 0.        ],
       [       inf, 1.        , 0.5       , 0.33333333],
       [       inf, 2.        , 1.        , 0.66666667],
       [       inf, 3.        , 1.5       , 1.        ]])

In [84]:
gen =(i*i for i in range(5))

In [81]:
def test(x):
    yield x

In [82]:
test(5)

<generator object test at 0x0000022718234C10>

In [86]:
np.fromiter(gen,dtype = int)

array([ 0,  1,  4,  9, 16])